export const ACCESS = {
    DASHBOARD: "DASHBOARD",
    SHIFT: "SHIFT",
    RUANGAN: "RUANGAN",
    MATA_KULIAH: "MATA_KULIAH",
    MAHASISWA: "MAHASISWA",
    DOSEN: "DOSEN",
    JADWAL: "JADWAL",
    PENDAFTARAN_ASISTEN_LAB: "PENDAFTARAN_ASISTEN_LAB",
    PENERIMAAN_ASISTEN_LAB: "PENERIMAAN_ASISTEN_LAB",
    USER_MANAGEMENT: "USER_MANAGEMENT",
    ROLE_MANAGEMENT: "ROLE_MANAGEMENT",
};
